/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Batchable, BatchableInterface } from "../Batchable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "innerError",
        type: "bytes",
      },
    ],
    name: "BatchError",
    type: "error",
  },
];

export class Batchable__factory {
  static readonly abi = _abi;
  static createInterface(): BatchableInterface {
    return new utils.Interface(_abi) as BatchableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Batchable {
    return new Contract(address, _abi, signerOrProvider) as Batchable;
  }
}
