/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IIDrissRegistry,
  IIDrissRegistryInterface,
} from "../IIDrissRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_address",
        type: "string",
      },
    ],
    name: "IDrissOwners",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "hashPub",
        type: "string",
      },
    ],
    name: "getIDriss",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IIDrissRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IIDrissRegistryInterface {
    return new utils.Interface(_abi) as IIDrissRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIDrissRegistry {
    return new Contract(address, _abi, signerOrProvider) as IIDrissRegistry;
  }
}
