/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as libs from "./libs";
export * as mocks from "./mocks";
export { Tipping__factory } from "./Tipping__factory";
