/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface FeeCalculatorSimpleInterface extends ethers.utils.Interface {
  functions: {
    "MINIMAL_PAYMENT_FEE()": FunctionFragment;
    "PAYMENT_FEE_PERCENTAGE()": FunctionFragment;
    "PAYMENT_FEE_PERCENTAGE_DENOMINATOR()": FunctionFragment;
    "PAYMENT_FEE_SLIPPAGE_PERCENT()": FunctionFragment;
    "changeMinimalPaymentFee(uint256)": FunctionFragment;
    "changePaymentFeePercentage(uint256,uint256)": FunctionFragment;
    "getPaymentFee(uint256,uint8)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MINIMAL_PAYMENT_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAYMENT_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAYMENT_FEE_PERCENTAGE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAYMENT_FEE_SLIPPAGE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeMinimalPaymentFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changePaymentFeePercentage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "MINIMAL_PAYMENT_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAYMENT_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAYMENT_FEE_PERCENTAGE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAYMENT_FEE_SLIPPAGE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeMinimalPaymentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changePaymentFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class FeeCalculatorSimple extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FeeCalculatorSimpleInterface;

  functions: {
    MINIMAL_PAYMENT_FEE(overrides?: CallOverrides): Promise<[BigNumber]>;

    PAYMENT_FEE_PERCENTAGE(overrides?: CallOverrides): Promise<[BigNumber]>;

    PAYMENT_FEE_PERCENTAGE_DENOMINATOR(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    PAYMENT_FEE_SLIPPAGE_PERCENT(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    changeMinimalPaymentFee(
      _minimalPaymentFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changePaymentFeePercentage(
      _paymentFeePercentage: BigNumberish,
      _paymentFeeDenominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPaymentFee(
      _value: BigNumberish,
      _assetType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  MINIMAL_PAYMENT_FEE(overrides?: CallOverrides): Promise<BigNumber>;

  PAYMENT_FEE_PERCENTAGE(overrides?: CallOverrides): Promise<BigNumber>;

  PAYMENT_FEE_PERCENTAGE_DENOMINATOR(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  PAYMENT_FEE_SLIPPAGE_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

  changeMinimalPaymentFee(
    _minimalPaymentFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changePaymentFeePercentage(
    _paymentFeePercentage: BigNumberish,
    _paymentFeeDenominator: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPaymentFee(
    _value: BigNumberish,
    _assetType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MINIMAL_PAYMENT_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    PAYMENT_FEE_PERCENTAGE(overrides?: CallOverrides): Promise<BigNumber>;

    PAYMENT_FEE_PERCENTAGE_DENOMINATOR(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PAYMENT_FEE_SLIPPAGE_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    changeMinimalPaymentFee(
      _minimalPaymentFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changePaymentFeePercentage(
      _paymentFeePercentage: BigNumberish,
      _paymentFeeDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getPaymentFee(
      _value: BigNumberish,
      _assetType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    MINIMAL_PAYMENT_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    PAYMENT_FEE_PERCENTAGE(overrides?: CallOverrides): Promise<BigNumber>;

    PAYMENT_FEE_PERCENTAGE_DENOMINATOR(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PAYMENT_FEE_SLIPPAGE_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    changeMinimalPaymentFee(
      _minimalPaymentFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changePaymentFeePercentage(
      _paymentFeePercentage: BigNumberish,
      _paymentFeeDenominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPaymentFee(
      _value: BigNumberish,
      _assetType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MINIMAL_PAYMENT_FEE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PAYMENT_FEE_PERCENTAGE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PAYMENT_FEE_PERCENTAGE_DENOMINATOR(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PAYMENT_FEE_SLIPPAGE_PERCENT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeMinimalPaymentFee(
      _minimalPaymentFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changePaymentFeePercentage(
      _paymentFeePercentage: BigNumberish,
      _paymentFeeDenominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPaymentFee(
      _value: BigNumberish,
      _assetType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
