/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MockEASInterface extends ethers.utils.Interface {
  functions: {
    "attest((bytes32,(address,uint64,bool,bytes32,bytes,uint256)))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "attest",
    values: [
      {
        schema: BytesLike;
        data: {
          recipient: string;
          expirationTime: BigNumberish;
          revocable: boolean;
          refUID: BytesLike;
          data: BytesLike;
          value: BigNumberish;
        };
      }
    ]
  ): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;

  events: {
    "Attested(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Attested"): EventFragment;
}

export type AttestedEvent = TypedEvent<[string] & { recipient: string }>;

export class MockEAS extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MockEASInterface;

  functions: {
    attest(
      request: {
        schema: BytesLike;
        data: {
          recipient: string;
          expirationTime: BigNumberish;
          revocable: boolean;
          refUID: BytesLike;
          data: BytesLike;
          value: BigNumberish;
        };
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  attest(
    request: {
      schema: BytesLike;
      data: {
        recipient: string;
        expirationTime: BigNumberish;
        revocable: boolean;
        refUID: BytesLike;
        data: BytesLike;
        value: BigNumberish;
      };
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    attest(
      request: {
        schema: BytesLike;
        data: {
          recipient: string;
          expirationTime: BigNumberish;
          revocable: boolean;
          refUID: BytesLike;
          data: BytesLike;
          value: BigNumberish;
        };
      },
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "Attested(address)"(
      recipient?: string | null
    ): TypedEventFilter<[string], { recipient: string }>;

    Attested(
      recipient?: string | null
    ): TypedEventFilter<[string], { recipient: string }>;
  };

  estimateGas: {
    attest(
      request: {
        schema: BytesLike;
        data: {
          recipient: string;
          expirationTime: BigNumberish;
          revocable: boolean;
          refUID: BytesLike;
          data: BytesLike;
          value: BigNumberish;
        };
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    attest(
      request: {
        schema: BytesLike;
        data: {
          recipient: string;
          expirationTime: BigNumberish;
          revocable: boolean;
          refUID: BytesLike;
          data: BytesLike;
          value: BigNumberish;
        };
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
