/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SendToHashUtilsMockInterface extends ethers.utils.Interface {
  functions: {
    "fromHexChar(uint8)": FunctionFragment;
    "hashIDrissWithPassword(string,string)": FunctionFragment;
    "safeHexStringToAddress(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "fromHexChar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashIDrissWithPassword",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeHexStringToAddress",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "fromHexChar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashIDrissWithPassword",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeHexStringToAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class SendToHashUtilsMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SendToHashUtilsMockInterface;

  functions: {
    fromHexChar(c: BigNumberish, overrides?: CallOverrides): Promise<[number]>;

    hashIDrissWithPassword(
      _IDrissHash: string,
      _password: string,
      overrides?: CallOverrides
    ): Promise<[string] & { _hash: string }>;

    safeHexStringToAddress(
      s: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  fromHexChar(c: BigNumberish, overrides?: CallOverrides): Promise<number>;

  hashIDrissWithPassword(
    _IDrissHash: string,
    _password: string,
    overrides?: CallOverrides
  ): Promise<string>;

  safeHexStringToAddress(s: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    fromHexChar(c: BigNumberish, overrides?: CallOverrides): Promise<number>;

    hashIDrissWithPassword(
      _IDrissHash: string,
      _password: string,
      overrides?: CallOverrides
    ): Promise<string>;

    safeHexStringToAddress(
      s: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    fromHexChar(c: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    hashIDrissWithPassword(
      _IDrissHash: string,
      _password: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    safeHexStringToAddress(
      s: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fromHexChar(
      c: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashIDrissWithPassword(
      _IDrissHash: string,
      _password: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    safeHexStringToAddress(
      s: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
