/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetMockSol from "./AssetMock.sol";
export type { assetMockSol };
export type { MaticPriceAggregatorV3Mock } from "./MaticPriceAggregatorV3Mock";
export type { MockEAS } from "./MockEAS";
