/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as attestationSol from "./Attestation.sol";
export { FeeCalculator__factory } from "./FeeCalculator__factory";
export { MultiAssetSender__factory } from "./MultiAssetSender__factory";
