/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type BatchCallStruct = {
  assetType: BigNumberish;
  recipient: AddressLike;
  amount: BigNumberish;
  tokenId: BigNumberish;
  tokenAddress: AddressLike;
  message: string;
};

export type BatchCallStructOutput = [
  assetType: bigint,
  recipient: string,
  amount: bigint,
  tokenId: bigint,
  tokenAddress: string,
  message: string
] & {
  assetType: bigint;
  recipient: string;
  amount: bigint;
  tokenId: bigint;
  tokenAddress: string;
  message: string;
};

export type AdjustedBatchCallStruct = {
  assetType: BigNumberish;
  recipient: AddressLike;
  amount: BigNumberish;
  tokenId: BigNumberish;
  tokenAddress: AddressLike;
  message: string;
  nativeAmount: BigNumberish;
};

export type AdjustedBatchCallStructOutput = [
  assetType: bigint,
  recipient: string,
  amount: bigint,
  tokenId: bigint,
  tokenAddress: string,
  message: string,
  nativeAmount: bigint
] & {
  assetType: bigint;
  recipient: string;
  amount: bigint;
  tokenId: bigint;
  tokenAddress: string;
  message: string;
  nativeAmount: bigint;
};

export interface FeeCalculatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FALLBACK_DECIMALS"
      | "FALLBACK_PRICE"
      | "FEE_TYPE_MAPPING"
      | "MINIMAL_PAYMENT_FEE"
      | "MINIMAL_PAYMENT_FEE_DENOMINATOR"
      | "NATIVE_USD_STALE_THRESHOLD"
      | "NATIVE_WEI_MULTIPLIER"
      | "PAYMENT_FEE_PERCENTAGE"
      | "PAYMENT_FEE_PERCENTAGE_DENOMINATOR"
      | "PAYMENT_FEE_SLIPPAGE_PERCENT"
      | "calculateBatchFee"
      | "changeMinimalPaymentFee"
      | "changePaymentFeePercentage"
      | "checkSequencer"
      | "getPaymentFee"
      | "getPaymentFeePost"
      | "owner"
      | "publicGoods"
      | "renounceOwnership"
      | "supportedERC20"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OracleFailed" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FALLBACK_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FALLBACK_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_TYPE_MAPPING",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMAL_PAYMENT_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMAL_PAYMENT_FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NATIVE_USD_STALE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NATIVE_WEI_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAYMENT_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAYMENT_FEE_PERCENTAGE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAYMENT_FEE_SLIPPAGE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateBatchFee",
    values: [BatchCallStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "changeMinimalPaymentFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changePaymentFeePercentage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSequencer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentFee",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentFeePost",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publicGoods",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedERC20",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FALLBACK_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FALLBACK_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_TYPE_MAPPING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMAL_PAYMENT_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMAL_PAYMENT_FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NATIVE_USD_STALE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NATIVE_WEI_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAYMENT_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAYMENT_FEE_PERCENTAGE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAYMENT_FEE_SLIPPAGE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateBatchFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeMinimalPaymentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changePaymentFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSequencer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentFeePost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicGoods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OracleFailedEvent {
  export type InputTuple = [reason: string];
  export type OutputTuple = [reason: string];
  export interface OutputObject {
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeeCalculator extends BaseContract {
  connect(runner?: ContractRunner | null): FeeCalculator;
  waitForDeployment(): Promise<this>;

  interface: FeeCalculatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FALLBACK_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  FALLBACK_PRICE: TypedContractMethod<[], [bigint], "view">;

  FEE_TYPE_MAPPING: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  MINIMAL_PAYMENT_FEE: TypedContractMethod<[], [bigint], "view">;

  MINIMAL_PAYMENT_FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  NATIVE_USD_STALE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  NATIVE_WEI_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  PAYMENT_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  PAYMENT_FEE_PERCENTAGE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PAYMENT_FEE_SLIPPAGE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  calculateBatchFee: TypedContractMethod<
    [calls: BatchCallStruct[]],
    [AdjustedBatchCallStructOutput[]],
    "view"
  >;

  changeMinimalPaymentFee: TypedContractMethod<
    [_minimalPaymentFee: BigNumberish, _paymentFeeDenominator: BigNumberish],
    [void],
    "nonpayable"
  >;

  changePaymentFeePercentage: TypedContractMethod<
    [_paymentFeePercentage: BigNumberish, _paymentFeeDenominator: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkSequencer: TypedContractMethod<[], [boolean], "view">;

  getPaymentFee: TypedContractMethod<
    [_value: BigNumberish, _assetType: BigNumberish, _recipient: AddressLike],
    [bigint],
    "view"
  >;

  getPaymentFeePost: TypedContractMethod<
    [_value: BigNumberish, _assetType: BigNumberish, _recipient: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  publicGoods: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  supportedERC20: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FALLBACK_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FALLBACK_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_TYPE_MAPPING"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINIMAL_PAYMENT_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINIMAL_PAYMENT_FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NATIVE_USD_STALE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NATIVE_WEI_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAYMENT_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAYMENT_FEE_PERCENTAGE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAYMENT_FEE_SLIPPAGE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateBatchFee"
  ): TypedContractMethod<
    [calls: BatchCallStruct[]],
    [AdjustedBatchCallStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "changeMinimalPaymentFee"
  ): TypedContractMethod<
    [_minimalPaymentFee: BigNumberish, _paymentFeeDenominator: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changePaymentFeePercentage"
  ): TypedContractMethod<
    [_paymentFeePercentage: BigNumberish, _paymentFeeDenominator: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkSequencer"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getPaymentFee"
  ): TypedContractMethod<
    [_value: BigNumberish, _assetType: BigNumberish, _recipient: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaymentFeePost"
  ): TypedContractMethod<
    [_value: BigNumberish, _assetType: BigNumberish, _recipient: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publicGoods"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedERC20"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OracleFailed"
  ): TypedContractEvent<
    OracleFailedEvent.InputTuple,
    OracleFailedEvent.OutputTuple,
    OracleFailedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OracleFailed(string)": TypedContractEvent<
      OracleFailedEvent.InputTuple,
      OracleFailedEvent.OutputTuple,
      OracleFailedEvent.OutputObject
    >;
    OracleFailed: TypedContractEvent<
      OracleFailedEvent.InputTuple,
      OracleFailedEvent.OutputTuple,
      OracleFailedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
