/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attestationSol from "./Attestation.sol";
export type { attestationSol };
export type { FeeCalculator } from "./FeeCalculator";
export type { MultiAssetSender } from "./MultiAssetSender";
