/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDriss } from "./IDriss";
export type { MockERC1155 } from "./MockERC1155";
export type { MockNFT } from "./MockNFT";
export type { MockToken } from "./MockToken";
